### ISSUE TITLE
Create project skeleton.

### ISSUE THREAD

**Issue by the-t-in-rtf** [fluid-lab/gamepad-navigator#1]
Before we get too far with the code of the project, it would be useful to set up a proper skeleton for the project:

1. We need to generate the initial `package.json` file, including author credits.
2. We need to add infusion as a dependency (use the latest "mainline" dev release, `3.0.0-dev.20200326T173810Z.24ddb2718`).
3. We need dev dependencies for our linting tools.
     1. [`eslint`](https://eslint.org)
     2. [`eslint-config-fluid`](https://github.com/fluid-project/eslint-config-fluid)
     3. [`gpii-grunt-lint-all`](https://github.com/GPII/gpii-grunt-lint-all)
4. We need a `Gruntfile.js` to configure the linting (see the documentation for gpii-grunt-lint-all for examples).
5. The README should describe briefly the purpose of the project.

If you'd like to see working examples, see [Infusion itself](https://github.com/fluid-project/infusion) and [gpii-handlebars](https://github.com/GPII/gpii-handlebars)

**Comment by dmahajan980** [comment]
We should also consider adding a `.gitignore` file to avoid any unwanted files being committed to the repository.
