### ISSUE TITLE
No means to open "select" dropdown directly.

### ISSUE THREAD

**Issue by dmahajan980** [fluid-lab/gamepad-navigator#15]
Currently, there's no direct way of opening or expanding `select` dropdown menus using JavaScript methods, such as `click`.
(_[Read more](https://stackoverflow.com/questions/430237/is-it-possible-to-use-js-to-open-an-html-select-to-show-its-option-list)_)

The way we are handling this is by using/toggling the `size` attribute. However, this should be replaced when we find anything that officially supports opening and closing standard `select` dropdowns in the future.

**Comment by duhrer** [comment]
I think we may need to close this one, there's still no better way to do it.
