### ISSUE TITLE
Issues with clicks and focus and various UI elements.

### ISSUE THREAD

**Issue by the-t-in-rtf** [fluid-lab/gamepad-navigator#20]
I did some extensive testing with a range of sites checking for issues, and found a few cases where the focus/highlighting don't seem to be working correctly with our simulated "click" and "tab/shift tab" actions.

I first noticed it with [this single-page app that I use often](https://intro.novationmusic.com/future-house-fusion). Try navigating to a non-highlighted instrument (such as "Retro Grain") using tabs and then hit enter.  You'll see that the previously selected instrument is no longer highlighted.  If I use the gamepad to attempt to do the same, the previously selected instrument stays highlighted.

This might just be an oddly written app, but to me suggested a wider pattern that might be an issue.  To check that, I tried the navigation bar demos for two commonly-used UI frameworks, Foundation Sites and Twitter Bootstrap.

First, I looked at [the Foundation sites documentation](https://get.foundation/sites/docs/dropdown-menu.html#Item-1).  Using a keyboard and mouse, I can navigate to their first demo navigation.  If I hit enter to open "Item 2", then shift+tab back to "Item 1", and hit enter, the "Item 2" menu closes and the "Item 1" menu opens.  The same doesn't happen with the gamepad.  I can't seem to open either the "Item 1" or "Item 2" menu with the gamepad button.  The "Item 3" button does seem to work.

I also tried it with Bootstrap on their [nav bar documentation](https://getbootstrap.com/docs/4.5/components/navbar/#content).  If you tab down to their first navbar example and hit enter when "Dropdown" is highlighted, the menu opens.  If you hit shift+tab, the menu is closed and the previous nav bar heading is highlighted.  If you try to do the same with the gamepad navigator, the menu doesn't close until you click the link.

We need to understand if there's a part of the process we're missing, for example, triggering `blur` on the element we're exiting as well as triggering `focus` on the next element.

**Comment by dmahajan980** [comment]
> I first noticed it with this single-page app that I use often. Try navigating to a non-highlighted instrument (such as "Retro Grain") using tabs and then hit enter. You'll see that the previously selected instrument is no longer highlighted. If I use the gamepad to attempt to do the same, the previously selected instrument stays highlighted.

@the-t-in-rtf I tried this app, and it's working with the gamepad as it should with the keyboard, i.e., if I select one instrument using the gamepad and then navigate to other option and select it, it's working fine. It might be possible that they have updated their app, but please let me know if you still see this issue.

Meanwhile, I'll go through the other parts of this ticket and will leave my notes as I find something.

**Comment by dmahajan980** [comment]
> I also tried it with Bootstrap on their nav bar documentation. If you tab down to their first navbar example and hit enter when "Dropdown" is highlighted, the menu opens. If you hit shift+tab, the menu is closed and the previous nav bar heading is highlighted. If you try to do the same with the gamepad navigator, the menu doesn't close until you click the link.

I was able to reproduce this issue, and I tried debugging using a couple of strategies. From what I inferred from reading the code for the [bootstrap dropdown](https://github.com/twbs/bootstrap/blob/main/js/src/dropdown.js), it seems that they have attached their custom event listeners to the "dropdown heading." These custom event listeners deal with its functionality, such as closing the dropdown menu when `Tab` key is pressed to move away from the dropdown heading and its options.

I could try thinking of some strategies to make it work (specific to "Bootstrap"), but I think it'll vary depending upon what version of Bootstrap is used. However, please let me know what you think about it, and we can proceed accordingly.

**Comment by dmahajan980** [comment]
> First, I looked at the Foundation sites documentation. Using a keyboard and mouse, I can navigate to their first demo navigation. If I hit enter to open "Item 2", then shift+tab back to "Item 1", and hit enter, the "Item 2" menu closes and the "Item 1" menu opens. The same doesn't happen with the gamepad. I can't seem to open either the "Item 1" or "Item 2" menu with the gamepad button. The "Item 3" button does seem to work.

I believe this framework is also using `keypress` event listeners for opening/closing the menu (as I could infer from the markup and custom attributes in their documentation). I'll try spending more time here to see if I'm wrong, but if it's the case I mentioned, I think we'll have to create an extended solution specific to the framework.

**Comment by the-t-in-rtf** [comment]
I see that the navigation works fine on the music site I mentioned.  It's interesting about the keypress hooks.  I wonder if we might be able to trigger a keypress hook with our own simulated event.  That might open up other possibilities for us in simulating arrow keys for web apps that support them.

**Comment by dmahajan980** [comment]
> I wonder if we might be able to trigger a keypress hook with our own simulated event. That might open up other possibilities for us in simulating arrow keys for web apps that support them.

@the-t-in-rtf I think it'll be worth looking into this and trying to find ways to trigger the "hooks" (or "listeners," if that's what you mean) even if there's a slim chance. However, in my opinion, it should be a separate ticket to work upon keeping in mind the scope of this issue.

**Comment by the-t-in-rtf** [comment]
So, this ticket started out as a bunch of examples of elements that weren't navigable using the code at a particular point in time.  I think it's fine to close this in favour of a more specific ticket describing the class of problem that remains, i.e. triggering UIs that rely on keypress rather than click handlers.

**Comment by dmahajan980** [comment]
@the-t-in-rtf I've created #53 for a more specific ticket. We can close this now.
