### ISSUE TITLE
Add documentation for all components, especially the input mapper.

### ISSUE THREAD

**Issue by the-t-in-rtf** [fluid-lab/gamepad-navigator#23]
The range of supported actions and options for input mappings has come to the point where it would be useful even for reviews to have a bit of documentation about the allowed/expected options, their meaning, and what each component is meant to do.

As an example of the format we have used in previous work, [check out this piece of the fluid-express documentation](https://github.com/fluid-project/fluid-express/blob/master/docs/headerMiddleware.md).  The key things that need to be covered at least briefly are:

1. What the component is meant to do.
2. What options it supports.
3. What invokers it provides, what parameters they accept, and what they return.

The style we have used previously is nowhere near as formal as JSDocs, but is similar in spirit.

**Comment by dmahajan980** [comment]
@the-t-in-rtf while I agree to use the same format you specified, I think we can enhance this if we use the [GitHub Wiki](https://docs.github.com/en/github/building-a-strong-community/about-wikis). It provides a sidebar that would make navigating from one section to another easy. Moreover, we can even choose to customize it as we want. The pages use markdown syntax, so it wouldn't be a problem to write and update it.

Keeping all these in mind, I propose to use it for the documentation. However, I am open to the format used in the [fluid-express documentation](https://github.com/fluid-project/fluid-express/tree/master/docs) or any other documentation platform that you believe is suitable for the purpose.

**Comment by the-t-in-rtf** [comment]
In general I prefer using documentation in the repository itself, as in my experience it reduces the context switching when you're adding a new feature and also updating the related documentation.  It's also a lot more accessible, as all of the content is literally expressed as textual characters.

However, I have certainly worked with projects that used a wiki for documentation in the past, so I'm open to the idea. I'd like to understand better how would we discuss and review a piece of documentation.  What mechanisms does the wiki provide to annotate or otherwise provide feedback in context?  How does the search work?  Is the editing interface accessible?

To help me understand, I think it would be good for you to create a simple home page for the project in the wiki as a test.  I'll take a look to see what options I have when looking at content someone else has created, and also look at the UI.
