### ISSUE TITLE
Add configuration panel to remap inputs.

### ISSUE THREAD

**Issue by the-t-in-rtf** [fluid-lab/gamepad-navigator#30]
Currently the default input mapping is hard coded.  We need to provide a configuration panel to allow user to select which functions are mapped to which controls.

Ideally, we would like for this to be at least keyboard navigable, as we've discussed it doesn't necessarily need to be controllable using the joystick (although it would be nice if we could manage it).

**Comment by dmahajan980** [comment]
We are still left with the input list part, i.e, to navigate to different inputs' configuration menu using a list instead of tabbing through each menu.
