### ISSUE TITLE
Issues with the configuration panel when closed accidentally.

### ISSUE THREAD

**Issue by dmahajan980** [fluid-lab/gamepad-navigator#38]
There are many cases where the user could accidentally close the panel without saving their changes. Adding a warning or saving the changes temporarily at least could solve the problem to a certain extent.

Upon digging further, I realized that it is not possible to keep the extension open or prevent it from closing, as their [FAQ says](https://developer.chrome.com/extensions/faq#faq-persist-popups). So the idea of a warning seems less likely, and the only possible way would be to store the changes separately. With this approach, we would have to create our mechanisms for clearing the data (if we want to store it temporarily), as the [Chrome Storage API](https://developer.chrome.com/extensions/storage) doesn't work like [sessionStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage).

To give a brief overview of the mechanism I'm thinking, it would store the changes side-by-side in Chrome's storage (separate from the stored configuration that the gamepad uses). So, if the user accidentally closes the panel, those changes would be reflected on the panel when opened again. In any case, the temporary changes would be deleted when the user saves the configuration using the "Save Changes" button.

While this might be the mechanism we later proceed with, I am open to other mechanisms, suggestions, and approaches that can be used.

**Comment by the-t-in-rtf** [comment]
I think that's a fine approach, really we're mainly guarding against things like accidentally hitting escape in the middle of editing preferences.  I do still think you should add a button to go back to the last saved settings either as part of this or separately.  "Discard Changes" is a common wording for this type of button.
