### ISSUE TITLE
The configuration panel should use the model to store the options rather than interrogating form elements directly.

### ISSUE THREAD

**Issue by the-t-in-rtf** [fluid-lab/gamepad-navigator#41]
Currently, the only place unsaved configuration options are stored is in the form elements themselves.  This requires trawling through the whole form to do things like determine whether there have been any changes.  It also means that as with #40, your code and markup are very tightly intertwined.

It would be cleaner to use something like [fluid-binder](https://github.com/fluid-project/fluid-binder) to associate component model data with form elements.  For example, when looking to see if the current state has unsaved changes or not, the toggling of the save/discard buttons could be tied to a model listener.  If you clearly express the "bindings" between form elements and model data as a serious of declarative options, your model logic does not even have to be aware of the markup.  This gives you more freedom in refactoring and improves the reusability of the codebase.

You would still need to store the last saved state and compare that to the current model, which you could do using the [`fluid.model.diff` function](https://github.com/fluid-project/infusion/blob/master/src/framework/core/js/DataBinding.js#L1425).

**Comment by duhrer** [comment]
With the work on #103, this issue is no longer relevant.
