### ISSUE TITLE
Extension icon stays hidden under the extensions menu

### ISSUE THREAD

**Issue by dmahajan980** [fluid-lab/gamepad-navigator#44]
Currently, the extension icon doesn't show up on the extensions menu when it's reloaded or installed. A Chrome user has to pin the extension to the taskbar to open the configuration panel using their mouse. So we would like the default behavior for this to be pinned to the extensions menu when installed, ensuring that the users won't have to do it by themselves.

**Comment by dmahajan980** [comment]
@the-t-in-rtf so I did some research on this, but couldn't find any relevant solution. So I created a [thread](https://support.google.com/chrome/thread/62469131?hl=en&msgid=62477028) on their discussion platform, and sadly, even they specified that there's no way to pin the extension automatically.

I feel that we should add a note in our documentation (while addressing #23) to let our users know that they need to pin the extension. Also, we should label this as "won't fix" or something similar as there isn't any way to fix this issue (unless the Chromium team changes it in the future).

**Comment by the-t-in-rtf** [comment]
I guess I got the wrong impression because the behaviour is the opposite in Opera (which is also derived from chromium).  It's fine to leave it open for now in case there are new options later on, I'd rather do that than close as "won't fix", as obviously we would fix it if we could.
