### ISSUE TITLE
Issues with triggering UI event handlers that rely on keypress

### ISSUE THREAD

**Issue by dmahajan980** [fluid-lab/gamepad-navigator#53]
Modern browsers, such as Chrome (in our case), prevent triggering of keypress and other keyboard events on behalf of a user due to various security concerns. But as discussed in #20, various web frameworks rely on these events for triggering changes to the UI through custom listener functions attached to them. The current implementation of the project lacks triggering such events and/or their listeners/hooks, so we'd like to have something that can trigger these hooks (at least for **click** event).

**Comment by duhrer** [comment]
In later work in the area, it seems like we really don't have any good options, most browser form elements ignore keyboard events that weren't directly triggered by a user.  The best we can typically do is updating the value of a form element.

We may have to just live with triggering mouse-like events, which don't have the same security issues.

**Comment by duhrer** [comment]
Later work on form editing and helpers has largely addressed this.  I'd rather close this out and open new issues if we find additional form elements that have problems.
