### ISSUE TITLE
Convert the inputIdentifier parameter encoding convention in the configurationPanel component to dot-notation 

### ISSUE THREAD

**Issue by dmahajan980** [fluid-lab/gamepad-navigator#58]
As discussed in #56, we should not use the current data encoding convention for gamepad input (for example, `button-0`), as we pass it in the form of `inputIdentifier` argument. It would be ideal to align this with what Infusion's [`fluid.get`](https://docs.fluidproject.org/infusion/development/CoreAPI.html#fluidgetmodel-path) and `fluid.put` support, i.e. the dot-notation and use that instead. For example, using `button.0` instead of `button-0`.

**Comment by dmahajan980** [comment]
The changes should be made in the code as well as the documentation.

**Comment by duhrer** [comment]
In the upcoming 1.0 release, the configuration panel has been removed in favour of the new settings page (see #103).  As a result this work no longer needs to be done.
