### ISSUE TITLE
Add support for navigating using "scanning".

### ISSUE THREAD

**Issue by the-t-in-rtf** [fluid-lab/gamepad-navigator#78]
[Switch Access Scanning](https://en.wikipedia.org/wiki/Switch_access_scanning) covers a range of strategies for people to navigate content using a limited range of inputs, such as:

1. Scanning through content and having the user hit a button to select the desired item when it is highlighted.
2. Scanning through content when a button is pressed and having the user release the button to select the desired item when it is highlighted.
3. Have one button to scan forward, another to scan backward, and a third to select a desired item when it is highlighted.

Our current approach supports some variations on the third option, so I think it's not unreasonable to think we could do the others.  We might choose to implement options 1 and 2 with a configurable limit on the number of items to scan before the user has to press a button to scan further.

We should also educate ourselves more about the range of strategies used, it may be that with a little thought we can address some of the feedback from the design critique and make a grid-based navigation strategy that would allow us to support something like the row/column scanning described in the linked Wikipedia page.

**Comment by duhrer** [comment]
I have given this some thought, one way to support this would be to:

1. Add support for "repeating" keys as outlined in #77 
2. Add a new type of "latched" binding, where a button is treated as held down it's pressed again.

**Comment by duhrer** [comment]
Now that any key (including the bumper navigation) can be configured to repeat, I think we can close this one out for now.  With the current code you can support two button navigation, i.e. hold the bumper button, and then click on the desired option when it's highlighted.  We can't support one button navigation where releasing clicks automatically, nor do we support "latching", but we should wait for people to request this and provide details on how they want to use those features.
