### ISSUE TITLE
To Change Face Buttons of Game Controller

### ISSUE THREAD

**Issue by SHIVAJI07** [fluid-lab/gamepad-navigator#79]
## Is your feature request related to a problem?
**yes, it is reagarding face buttons. actually Numbers which are inside face buttons are not visible properly.**

## Describe the solution you'd like
**I would like to change the colour and design it properly**

## Describe alternative solutions you've considered
**I would also like to improve color and theme for Game Controller.**

![game controller](https://user-images.githubusercontent.com/69622677/102611017-32c8a280-4154-11eb-816e-16657a91a3d7.jpg)

**Comment by duhrer** [comment]
The new administrative interface (see #103) does not use this diagram any longer.  Instead it lists all available bindings for buttons and axes.  I will close out this issue for now, if we decide to reintroduce a diagram view of bindings, we can write that up separately.
