### ISSUE TITLE
Add ability to search and/or input a URL.

### ISSUE THREAD

**Issue by the-t-in-rtf** [fluid-lab/gamepad-navigator#85]
The gamepad navigator currently provides the ability to navigate from whatever starting point you're on, and only by clicking links. It would be an improvement if users could navigate to a new page by inputing a URL.

Depends on #84.

**Comment by the-t-in-rtf** [comment]
A key question here is whether we can send simulated keyboard input directly to the location bar in Chrome.  If we can, then:

1. We don't have to make our own text input.
2. Users can benefit from the auto-complete built into the location bar.

**Comment by jobara** [comment]
I haven't seen any apis that would seem to give the features that you want. There's the [omnibox api](https://developer.chrome.com/docs/extensions/reference/omnibox/), but that works more in the reverse, allowing you to handle input from the omnibox. There's also the [search api](https://developer.chrome.com/docs/extensions/reference/search/). This would seem to be the closest, although I don't think it will update the omnibox and allow for auto-complete.

**Comment by the-t-in-rtf** [comment]
I made a simple one-off to test the search API.  It's OK for just a hostname, the first search result is usually a link to the site.  It's not great for anything with a path, as it treats those as words and generally does not result in the desired URL appearing in the search results.   Seems like we should eventually support both, wondering at the moment which provides the most initial value.  I'm kind of leaning towards search, but will think about it.

The thing is, once we implement a gamepad-controllable keyboard, adding the other one won't be much work, so really we could go either way.

**Comment by the-t-in-rtf** [comment]
I just remembered a major blocker for this.  The gamepad navigator currently has no way of allowing gamepad controls in its extension pages.  We'd need to figure out an approach to doing that as a prerequisite of adding an onscreen keyboard.

I'm wondering if we can open a new window that points to static content within our package.  It would offer a new option for configuring the bindings as well.

**Comment by the-t-in-rtf** [comment]
I created a one-off extension and was able to confirm that we can present arbitrary HTML as a panel/popup/page.  Inline scripts are prohibited up front, but we can source external scripts just fine.  So, we should be able to present an onscreen dialog of our own this way and run whatever client-side code we want.

I need to confirm whether our gamepad navigation code is running in that context (so that we can use the default key bindings to navigate).  Also need to confirm that we can load the user's preferences from storage.

If not, we'll have to create a simplified navigation scheme similar to the menus on consoles where:

1. Both thumbsticks and the d-pad navigate up/down/left/right.
2. Button 0 is "yes" (click, enter, etc.).
3. Button 1 is "no" (escape, etc.).

I was initially worried about focus management, but if we always consider this command to be leading to a "new tab" or "new window", the window/tab navigation functions are enough to manage things from there.

**Comment by duhrer** [comment]
I realised earlier that part of the need for this comes from not being able to reach/use the location bar with the gamepad.  If possible, it would be nice to suggest URLs from history as completions, like the location bar does.

**Comment by duhrer** [comment]
We're getting close to this, now that the work on the onscreen keyboard is nearing completion.  I have had a bit of a change of thought regarding displaying suggested completions. This seems like the kind of thing that works with a keyboard or mouse, but would involve a lot of navigation to use in the context of the gamepad navigator.

Instead, I'm thinking more along the lines of making this like the location bar without suggested completions:

1.  If a URL is entered, that URL is opened.
2. If anything else is entered, the [default search provider is searched using the Chrome Extension API](https://developer.chrome.com/docs/extensions/reference/search/).

I was also thinking about the text entry.  It seems confusing and difficult to go from a search input modal to the keyboard modal.  Instead I will make a separate modal where the onscreen keyboard can only be used to enter a URL.  This would be the first modal with a button other than "close", something like "launch".

**Comment by duhrer** [comment]
I'm getting very close on this, but have mainly been focused on getting the search working.  Looking at the time involved in entering an actual URL, I think it might be best to just leave it as a search for now.

**Comment by duhrer** [comment]
This work has been merged and will be part of the upcoming 1.0 release.
