### ISSUE TITLE
Update chrome extension manifest version.

### ISSUE THREAD

**Issue by duhrer** [fluid-lab/gamepad-navigator#90]
Loading the plugin now throws an error:

```
Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.
```

We need to update our manifest version by the end of the year.

**Comment by dmahajan980** [comment]
Hey @duhrer @the-t-in-rtf, I've been away for a very long time and trying to catch up through this issue. Can you please tell if anything was finalised on the bundling part and the major blockers (if any) that are preventing us from settling on a bundler?

**Comment by duhrer** [comment]
Hi, @dmahajan980.  I still need to look at this.  I will also create a ticket to add a privacy policy so that we can get the plugin added to the Chrome Web Store again.

**Comment by duhrer** [comment]
It seems like the new version is now required, so I suspect we'll have to address this before we can restore the web store listing.

**Comment by duhrer** [comment]
After reviewing the approach UIO+ used in migrating and reading [this helpful guide](https://css-tricks.com/how-to-transition-to-manifest-v3-for-chrome-extensions/), I have made a first pass at updating.  Thus far I have confirmed that the following work:

1.  The plugin bundles and loads without errors.
2.  The configuration interface and preferences storage work.

I am in the process of testing all methods.  Thus far I have confirmed the following working (in the order they appear in the configuration menu):

1. click
2. history back button
3. history next button
4. focus on the previous element
5. focus on the next element
6. scroll left
7. scroll right
8. scroll up
9. scroll down
10. switch to the previous tab
11. switch to the next tab
12. close current browser tab
13. close current browser window
14. zoom in on the active web page
15. zoom out on the active web page
16. maximise the current browser window
17. restore the size of the current browser window

The following don't seem to work, I will have to look into that further tomorrow:

1. Opening a new tab
2. Opening a new window.
3. Switching to the previous browser window
4. Switching to the next browser window
5. Re-open the last closed tab or window

**Comment by duhrer** [comment]
I have continued testing and will comment further on the pull.

**Comment by duhrer** [comment]
The work has been reviewed and the pull has been merged.
